'use client';

import { useState } from 'react';

const seoTags = {
  'Qatar — Doha & Cities': [
    '#DOHAcoco', '#DOHAWeeed', '#DOHAVapes', '#DOHAHTC', '#DOHASnow', '#DOHALarycai',
    '#DOHAIce', '#DOHALSD', '#DOHACBDoil', '#DOHAHashesh', '#DOHASmoking', '#DOHAplug',
    '#DohaLocation', '#DohaDelivery', '#Doha24x7', '#DohaPremium',
    '#ThePearlcoco', '#ThePearlVapes', '#ThePearlWeeed', '#ThePearlSnow', '#ThePearlHTC',
    '#WestBaycoco', '#WestBayWeeed', '#WestBayVapes',
    '#AlSaddcoco', '#AlSaddWeeed', '#AlSaddVapes',
    '#BinMahmoudcoco', '#BinMahmoudWeeed',
    '#MadinatKhalifacoco', '#MadinatKhalifaWeeed',
    '#Msheirebcoco', '#MsheirebWeeed',
    '#SouqWaqifcoco', '#SouqWaqifWeeed',
    '#Kataracoco', '#KataraWeeed', '#KataraVapes',
    '#IndustrialAreaDohacoco', '#IndustrialAreaDohaWeeed',
    '#LUSAILcoco', '#LUSAILVapes', '#LUSAILWeeed', '#LUSAILHTC', '#LUSAILSnow',
    '#LUSAILIce', '#LUSAILHashesh', '#LUSAILCBD', '#LUSAILplug',
    '#AlWAKRAHcoco', '#AlWAKRAHVapes', '#AlWAKRAHWeeed', '#AlWAKRAHSnow', '#AlWAKRAHHTC',
    '#AlWAKRAHHashesh', '#AlWAKRAHplug',
    '#SEALINEcoco', '#SEALINEVapes', '#SEALINEWeeed', '#SEALINESnow', '#SEALINEHashesh',
    '#MESAieedcoco', '#MESAieedVapes', '#MESAieedWeeed', '#MESAieedSnow',
    '#InlandSeaWeeed', '#InlandSeaCoco', '#InlandSeaVapes',
    '#AlKHORcoco', '#AlKHORVapes', '#AlKHORWeeed', '#AlKHORSnow', '#AlKHORHTC',
    '#PurpleIslandWeeed', '#PurpleIslandCoco',
    '#DUKHANcoco', '#DUKHANVapes', '#DUKHANWeeed',
    '#SALWAcoco', '#SALWAVapes', '#SALWAWeeed',
    '#FilmCitycoco', '#FilmCityWeeed',
    '#AlRAYYANcoco', '#AlRAYYANVapes', '#AlRAYYANWeeed', '#AlRAYYANSnow',
    '#AlRAYYANHTC', '#AlRAYYANHashesh',
    '#Qatarcoco', '#qatarweeed', '#qatarVape', '#QatarHTC', '#QatarLarycai',
    '#QatarIce', '#QatarLSD', '#QatarCBD', '#QatarHashesh', '#QatarSnow',
    '#QatarSmoking', '#QatarPlug', '#QatarDelivery', '#Qatar24x7',
    '#AllQatar', '#QatarLocation', '#QatarPremium',
  ],
  'Dubai — All Areas': [
    '#JUMEIRAHLAKETOWERCOCO', '#JLTweeed', '#JLTVapes', '#JLTSnow', '#JLTHTC',
    '#JLTcoco', '#JLTplug', '#JLTdelivery',
    '#DUBAIINTERCITYCOCO', '#DubaiIntercityWeeed', '#DubaiIntercityVapes',
    '#PalmJumeirahCOCO', '#PalmJumeirahWeeed', '#PalmJumeirahVapes', '#PalmJumeirahSnow',
    '#PalmJumeirahHTC', '#PalmJumeirahHashesh', '#PalmJumeirahplug',
    '#THEPALMJUMEIRAHCOCO', '#THEPALMJUMEIRAHWeeed',
    '#DUBAIMARINACOCO', '#DubaiMarinaWeeed', '#DubaiMarinaVapes', '#DubaiMarinaSnow',
    '#DUBAIMARINAWALKSnow', '#DubaiMarinaHTC', '#DubaiMarinaHashesh', '#DubaiMarinaplug',
    '#ALBARSHAcoco', '#AlBarshaWeeed', '#AlBarshaVapes', '#AlBarshaSnow', '#AlBarshaHTC',
    '#AlBarshaHashesh', '#AlBarshaCBD', '#AlBarshaLarycai', '#AlBarshaplug',
    '#ALBARSHAFIRSTVapesSnowCoco', '#ALBARSHAFIRSTWeeed', '#ALBARSHAFIRSTHTC',
    '#AlBARSHASOUTHSnowcocoVapes', '#AlBARSHASOUTHWeeed', '#AlBARSHASOUTHHTC',
    '#DubaiMiracleGardSnowCocoVapesLarycaiIceCBD', '#MiracleGardenWeeed',
    '#CircleMallbyDubaiRetail', '#CircleMallcoco', '#CircleMallVapes', '#CircleMallWeeed',
    '#SkiDubai', '#SkiDubaicoco', '#SkiDubaiVapes',
    '#AlQUOZ', '#AlQUOZcoco', '#AlQUOZVapes', '#AlQUOZWeeed', '#AlQUOZSnow',
    '#DubaiMoterCity', '#DubaiMotorCitycoco', '#DubaiMotorCityVapes', '#DubaiMotorCityWeeed',
    '#TheElsClub', '#TheElsClubcoco', '#TheElsClubVapes',
    '#JumeirahVillageCircle', '#JVCWeeed', '#JVCVapes', '#JvcLarycai', '#Jvccoco',
    '#JvcCoke', '#JVcSnow', '#JVCHTC', '#JVCHashesh', '#JVCplug',
    '#JumeirahVillageTrinangle', '#JVTWeeed', '#JVTVapes', '#JVTcoco', '#JVTSnow',
    '#JumeirahGolfEstates', '#JumeirahGolfEstatescoco', '#JGEweeed',
    '#DubaiProductionCity', '#DPCweeed', '#DPCVapes', '#DPCcoco',
    '#GolfCourse', '#GolfCourseWeed',
    '#JabalAliIndustrialFirst', '#JabalAliIndustrialcoco', '#JabalAliIndustrialVapes',
    '#JebelAliIndustrialArea', '#JebelAliWeeed', '#JebelAliVapes', '#JebelAlicoco',
    '#ExpoCityDubai', '#ExpoCitycoco', '#ExpoCityVapes', '#ExpoCityWeeed',
    '#GlobalVillage', '#GlobalVillagecoco', '#GlobalVillageVapes', '#GlobalVillageWeeed',
    '#DubaiFrame', '#DubaiFramecoco', '#DubaiFrameVapes',
    '#DubaiGoldSouk', '#DubaiGoldSoukcoco', '#GoldSoukVapes',
    '#JumeirahBeach', '#JumeirahBeachcoco', '#JumeirahBeachVapes', '#JumeirahBeachWeeed',
    '#DubaiSafariPark', '#DubaiSafariParkcoco', '#SafariParkVapes',
    '#AlMAMZAR', '#AlMAMZARcoco', '#AlMAMZARVapes', '#AlMAMZARWeeed',
    '#Jumeirah1', '#Jumeirah1coco', '#Jumeirah1Vapes', '#Jumeirah1Weeed', '#Jumeirah1Snow',
    '#Jumeirah2', '#Jumeirah2Weeed', '#Jumeirah2coco', '#Jumeirah2Vapes',
    '#Jumeirah3', '#Jumeirah3Weeed', '#Jumeirah3coco', '#Jumeirah3Vapes',
    '#BusinessBay', '#BusinessBaycoco', '#BusinessBayVapes', '#BusinessBayWeeed', '#BusinessBaySnow',
    '#DowntownDubai', '#DowntownDubaicoco', '#DowntownDubaiVapes', '#DowntownDubaiWeeed',
    '#DeiraDubai', '#Deiracoco', '#DeiraVapes', '#DeiraWeeed', '#DeiraSnow',
    '#BurDubai', '#BurDubaicoco', '#BurDubaiVapes', '#BurDubaiWeeed',
    '#DubaiInternationalCity', '#InternationalCitycoco', '#InternationalCityVapes',
    '#DiscoveryGardens', '#DiscoveryGardenscoco', '#DiscoveryGardensVapes',
    '#ArabianRanches', '#ArabianRanchescoco', '#ArabianRanchesVapes',
    '#Mirdif', '#Mirdifcoco', '#MirdifVapes', '#MirdifWeeed',
    '#DubaiSiliconOasis', '#DSOcoco', '#DSOVapes', '#DSOWeeed',
    '#DubaiHills', '#DubaiHillscoco', '#DubaiHillsVapes',
    '#DAMACHills', '#DAMACHillscoco', '#DAMACHillsVapes',
    '#PlumJumeirahWeeed', '#PlumJumeirahVapes', '#PlumJumeirahHtcPilis',
    '#PlumJumeirahcoco', '#PlumJumeirahSnow', '#PlumJumeirahHashesh', '#PlumJumeirahplug',
    '#Dubaicoco', '#dubaiweeed', '#dubaiVape', '#DubaiHtcpilis', '#DubaiLarycai',
    '#DubaiIce', '#DubaiLSD', '#DubaiCBD', '#DubaiHashesh', '#DubaiSnow',
    '#DubaiSmoking', '#DubaiPlug', '#DubaiDelivery', '#Dubai24x7',
    '#Alldubai', '#AlldubaiSmoking', '#dubaiLife', '#DubaiLocation',
    '#IneedSnowDubai', '#ineedVapeDubai', '#ineedCocDubai',
    '#DxbSnow', '#DxbSmoking', '#DXBCocoPlug', '#DXBplug',
  ],
  'UAE — All Emirates': [
    '#Abudahabi', '#AbudahabiSnow', '#Abudahabicoco', '#AbudahabiCoke',
    '#AbudahabiVapes', '#AbudahabiCBDoil', '#AbudahabiHtc', '#AbudahabiWeeed',
    '#AbuDhabiHashesh', '#AbuDhabiLarycai', '#AbuDhabiIce', '#AbuDhabiLSD',
    '#AbuDhabiSmoking', '#AbuDhabiPlug', '#AbuDhabiDelivery', '#AbuDhabi24x7',
    '#SharjahCoco', '#SharjahVapes', '#Sharjahweeed', '#SharjahSnow', '#SharjahHTC',
    '#SharjahHashesh', '#SharjahCBD', '#SharjahLarycai', '#SharjahIce',
    '#SharjahSmoking', '#SharjahPlug', '#SharjahDelivery',
    '#Alkhan', '#Alkhancoco', '#AlkhanVapes', '#AlkhanWeeed', '#AlkhanSnow',
    '#AlnoorIsland', '#AlnoorIslandcoco', '#AlnoorIslandVapes',
    '#SharjahinternationalAirport', '#SalfZone', '#SalfZonecoco',
    '#06Mall', '#06Mallcoco', '#06MallVapes', '#06MallWeeed',
    '#SharjahNationalPark', '#SharjahNationalParkcoco',
    '#WasitWeltandNaturePark', '#WasitWetlandcoco',
    '#AjmanCoco', '#AjmanSnow', '#AjmanVapes', '#Ajmanhtc', '#AjmanWeeed',
    '#AjmanHashesh', '#AjmanCBD', '#AjmanLarycai', '#AjmanIce',
    '#AjmanSmoking', '#AjmanPlug', '#AjmanDelivery',
    '#DaytoDayAlittihadAjman', '#AlSafiaPark', '#AlSafiaParkcoco',
    '#AlShaabVillage', '#AlShaabVillagecoco', '#KshishaPark', '#KshishaParkcoco',
    '#Pygmyzoo', '#Pygmyzoococo',
    '#AlAINWeeed', '#AlAINVapes', '#AlAINcoco', '#AlAINSnow', '#AlAINHTC',
    '#AlAINHashesh', '#AlAINCBD', '#AlAINplug',
    '#FujairahWeeed', '#FujairahVapes', '#Fujairahcoco', '#FujairahSnow',
    '#FujairahHTC', '#FujairahHashesh', '#Fujairahplug',
    '#RAKWeeed', '#RAKVapes', '#RAKcoco', '#RAKSnow', '#RAKHTC',
    '#RAKHashesh', '#RAKplug', '#RasAlKhaimahWeeed',
    '#UmmAlQuwainWeeed', '#UmmAlQuwaincoco', '#UmmAlQuwainVapes',
    '#Uae', '#UAEcoco', '#UAEweeed', '#UAEVapes', '#UAEHTC', '#UAEHashesh',
    '#UAECBD', '#UAELarycai', '#UAEIce', '#UAELSD', '#UAESnow',
    '#UAESmoking', '#UAEPlug', '#UAEDelivery', '#UAE24x7',
  ],
  'Saudi Arabia — All Cities': [
    '#Riyadhcoco', '#RiyadhVapes', '#RiyadhWeeed', '#RiyadhSnow', '#RiyadhHTC',
    '#RiyadhHashesh', '#RiyadhCBD', '#RiyadhLarycai', '#RiyadhIce', '#RiyadhLSD',
    '#RiyadhSmoking', '#RiyadhPlug', '#RiyadhDelivery', '#Riyadh24x7',
    '#Jeddahcoco', '#JeddahVapes', '#JeddahWeeed', '#JeddahSnow', '#JeddahHTC',
    '#JeddahHashesh', '#JeddahCBD', '#JeddahLarycai', '#JeddahIce',
    '#JeddahSmoking', '#JeddahPlug', '#JeddahDelivery',
    '#Dammamcoco', '#DammamVapes', '#DammamWeeed', '#DammamSnow', '#DammamHTC',
    '#DammamHashesh', '#DammamCBD', '#DammamPlug', '#DammamDelivery',
    '#Khobarcoco', '#KhobarVapes', '#KhobarWeeed', '#KhobarSnow', '#KhobarHTC',
    '#KhobarHashesh', '#KhobarCBD', '#KhobarPlug', '#KhobarDelivery',
    '#MakkahWeeed', '#Makkahcoco', '#MakkahVapes', '#MakkahSnow',
    '#MedinaWeeed', '#Medinacoco', '#MedinaVapes', '#MedinaSnow',
    '#Taifcoco', '#TaifVapes', '#TaifWeeed', '#TaifSnow',
    '#AbhaWeeed', '#Abhacoco', '#AbhaVapes', '#AbhaSnow',
    '#Jubailcoco', '#JubailVapes', '#JubailWeeed', '#JubailSnow',
    '#YanbuWeeed', '#Yanbucoco', '#YanbuVapes',
    '#DhahranWeeed', '#Dhahrancoco', '#DhahranVapes',
    '#TabukWeeed', '#Tabukcoco', '#BuraidahWeeed', '#HailWeeed',
    '#NajranWeeed', '#JizanWeeed', '#AlHofufWeeed',
    '#SaudiArabiacoco', '#SaudiWeed', '#KSAVapes', '#KSASnow', '#KSAcoco',
    '#KSAHTC', '#KSAHashesh', '#KSACBD', '#KSALarycai', '#KSAIce',
    '#KSASmoking', '#SaudiPlug', '#KSAPlug', '#KSADelivery', '#KSA24x7',
    '#GulfWeed', '#Gulfcoco', '#GulfVapes', '#GulfSnow', '#GulfHTC',
    '#GulfHashesh', '#GulfPlug', '#GulfDelivery', '#GulfSmoking',
  ],
  'Products — All Types': [
    '#Snow', '#coke', '#Hashesh', '#Hashish',
    '#Larycai300mg', '#Larycai450mg', '#Larycai150mgPfizer', '#Larycai', '#LarycaiPifzer',
    '#ice', '#LSD', '#coco', '#Weeed', '#Weed', '#Vape', '#Vapes',
    '#CBD', '#CBDoil', '#THCVapes', '#THC', '#WeeedVapes',
    '#htcpilis', '#Pilis', '#HTC', '#HTCpills',
    '#MoroccoHashish', '#MoroccanHash', '#hashesh',
    '#SnowDubai', '#SnowQatar', '#SnowUAE', '#SnowSaudi', '#SnowDoha',
    '#CocoDubai', '#CocoQatar', '#CocoUAE', '#CocoSaudi', '#CocoDoha',
    '#WeeedDubai', '#WeeedQatar', '#WeeedUAE', '#WeeedSaudi', '#WeeedDoha',
    '#VapesDubai', '#VapesQatar', '#VapesUAE', '#VapesSaudi', '#VapesDoha',
    '#CBDDubai', '#CBDQatar', '#CBDUAE', '#CBDSaudi', '#CBDDoha',
    '#THCDubai', '#THCQatar', '#THCUAE', '#THCSaudi', '#THCDoha',
    '#HTCDubai', '#HTCQatar', '#HTCUAE', '#HTCSaudi', '#HTCDoha',
    '#LarycaiDubai', '#LarycaiQatar', '#LarycaiUAE', '#LarycaiSaudi', '#LarycaiDoha',
    '#IceDubai', '#IceQatar', '#IceUAE', '#IceSaudi', '#IceDoha',
    '#LSDDubai', '#LSDQatar', '#LSDUE', '#LSDSaudi', '#LSDDoha',
    '#HasheshDubai', '#HasheshQatar', '#HasheshUAE', '#HasheshSaudi', '#HasheshDoha',
    '#LocationDrop', '#DeliveryService', '#FastDelivery', '#SameDayDelivery',
    '#24x7Delivery', '#DiscreetDelivery', '#PremiumProducts', '#TrustedPlug',
    '#AlldubaiSmoking', '#dubaiLife', '#Smoking', '#DxbSmoking', '#dubaiSmoking',
    '#SmokingLife', '#QatarSmoking', '#DohaSmoking', '#GulfSmoking',
    '#OnlineOrder', '#SecureDelivery', '#ExpressDelivery', '#NightDelivery',
    '#TopQuality', '#BestPlug', '#GulfConnection',
  ],
  'How People Find Us — Natural Search Queries': [
    'how to get coco in Dubai', 'how to get weed in Dubai', 'how to get vapes in Dubai',
    'how to get snow in Dubai', 'how to get HTC in Dubai', 'how to get hashesh in Dubai',
    'how to get Larycai in Dubai', 'how to get ice in Dubai', 'how to get LSD in Dubai',
    'how to get coco in Qatar', 'how to get weed in Qatar', 'how to get vapes in Qatar',
    'how to get snow in Qatar', 'how to get HTC in Qatar', 'how to get hashesh in Qatar',
    'how to get coco in Doha', 'how to get weed in Doha', 'how to get vapes in Doha',
    'how to get snow in Doha', 'how to get HTC in Doha', 'how to get hashesh in Doha',
    'how to get coco in UAE', 'how to get weed in UAE', 'how to get vapes in UAE',
    'how to get snow in UAE', 'how to get coco in Saudi Arabia',
    'how to get weed in Saudi Arabia', 'how to get vapes in Saudi Arabia',
    'how to get coco in Riyadh', 'how to get weed in Riyadh', 'how to get vapes in Riyadh',
    'how to get coco in Jeddah', 'how to get weed in Jeddah', 'how to get vapes in Jeddah',
    'how to get coco in Abu Dhabi', 'how to get weed in Abu Dhabi',
    'how to get vapes in Abu Dhabi', 'how to get snow in Abu Dhabi',
    'how to get coco in Sharjah', 'how to get weed in Sharjah',
    'how to get vapes in Sharjah', 'how to get coco in Ajman',
    'how to get weed in Ajman', 'how to get vapes in Ajman',
    'how can I get coco in Dubai', 'how can I get weed in Dubai',
    'how can I get vapes in Dubai', 'how can I get snow in Dubai',
    'how can I get HTC in Dubai', 'how can I get hashesh in Dubai',
    'how can I get Larycai in Dubai', 'how can I get ice in Dubai',
    'how can I get coco in Qatar', 'how can I get weed in Qatar',
    'how can I get vapes in Qatar', 'how can I get snow in Qatar',
    'how can I get HTC in Qatar', 'how can I get hashesh in Qatar',
    'how can I get coco in Doha', 'how can I get weed in Doha',
    'how can I get vapes in Doha', 'how can I get snow in Doha',
    'how can I get HTC in Doha', 'how can I get hashesh in Doha',
    'how can I get coco in UAE', 'how can I get weed in UAE',
    'how can I get vapes in UAE', 'how can I get snow in UAE',
    'how can I get coco in Saudi Arabia', 'how can I get weed in Saudi Arabia',
    'how can I get vapes in Saudi Arabia', 'how can I get snow in Saudi Arabia',
    'how can I get coco in Riyadh', 'how can I get weed in Riyadh',
    'how can I get vapes in Riyadh', 'how can I get snow in Riyadh',
    'how can I get coco in Jeddah', 'how can I get weed in Jeddah',
    'how can I get vapes in Jeddah', 'how can I get snow in Jeddah',
    'how can I get coco in Abu Dhabi', 'how can I get weed in Abu Dhabi',
    'how can I get vapes in Abu Dhabi', 'how can I get snow in Abu Dhabi',
    'how can I get coco in Sharjah', 'how can I get weed in Sharjah',
    'how can I get vapes in Sharjah', 'how can I get snow in Sharjah',
    'how can I get coco in Ajman', 'how can I get weed in Ajman',
    'how can I get vapes in Ajman', 'how can I get snow in Ajman',
    'where to buy coco in Dubai', 'where to buy weed in Dubai',
    'where to buy vapes in Dubai', 'where to buy snow in Dubai',
    'where to buy HTC in Dubai', 'where to buy hashesh in Dubai',
    'where to buy Larycai in Dubai', 'where to buy ice in Dubai',
    'where to buy coco in Qatar', 'where to buy weed in Qatar',
    'where to buy vapes in Qatar', 'where to buy snow in Qatar',
    'where to buy HTC in Qatar', 'where to buy hashesh in Qatar',
    'where to buy coco in Doha', 'where to buy weed in Doha',
    'where to buy vapes in Doha', 'where to buy snow in Doha',
    'where to buy HTC in Doha', 'where to buy hashesh in Doha',
    'where to buy coco in UAE', 'where to buy weed in UAE',
    'where to buy vapes in UAE', 'where to buy snow in UAE',
    'where to buy coco in Saudi Arabia', 'where to buy weed in Saudi Arabia',
    'where to buy vapes in Saudi Arabia', 'where to buy snow in Saudi Arabia',
    'where to buy coco in Riyadh', 'where to buy weed in Riyadh',
    'where to buy vapes in Riyadh', 'where to buy snow in Riyadh',
    'where to buy coco in Jeddah', 'where to buy weed in Jeddah',
    'where to buy vapes in Jeddah', 'where to buy snow in Jeddah',
    'where to buy coco in Abu Dhabi', 'where to buy weed in Abu Dhabi',
    'where to buy vapes in Abu Dhabi', 'where to buy snow in Abu Dhabi',
    'where to buy coco in Sharjah', 'where to buy weed in Sharjah',
    'where to buy vapes in Sharjah', 'where to buy snow in Sharjah',
    'where to buy coco in Ajman', 'where to buy weed in Ajman',
    'where to buy vapes in Ajman', 'where to buy snow in Ajman',
    'I need coco in Dubai', 'I need weed in Dubai', 'I need vapes in Dubai',
    'I need snow in Dubai', 'I need HTC in Dubai', 'I need hashesh in Dubai',
    'I need Larycai in Dubai', 'I need ice in Dubai', 'I need LSD in Dubai',
    'I need coco in Qatar', 'I need weed in Qatar', 'I need vapes in Qatar',
    'I need snow in Qatar', 'I need HTC in Qatar', 'I need hashesh in Qatar',
    'I need coco in Doha', 'I need weed in Doha', 'I need vapes in Doha',
    'I need snow in Doha', 'I need HTC in Doha', 'I need hashesh in Doha',
    'I need coco in UAE', 'I need weed in UAE', 'I need vapes in UAE',
    'I need snow in UAE', 'I need coco in Saudi Arabia',
    'I need weed in Saudi Arabia', 'I need vapes in Saudi Arabia',
    'I need coco in Riyadh', 'I need weed in Riyadh', 'I need vapes in Riyadh',
    'I need coco in Jeddah', 'I need weed in Jeddah', 'I need vapes in Jeddah',
    'I need coco in Abu Dhabi', 'I need weed in Abu Dhabi',
    'I need vapes in Abu Dhabi', 'I need snow in Abu Dhabi',
    'I need coco in Sharjah', 'I need weed in Sharjah',
    'I need vapes in Sharjah', 'I need coco in Ajman',
    'I need weed in Ajman', 'I need vapes in Ajman',
    'coco delivery in Dubai', 'weed delivery in Dubai', 'vapes delivery in Dubai',
    'snow delivery in Dubai', 'HTC delivery in Dubai', 'hashesh delivery in Dubai',
    'Larycai delivery in Dubai', 'ice delivery in Dubai', 'LSD delivery in Dubai',
    'coco delivery in Qatar', 'weed delivery in Qatar', 'vapes delivery in Qatar',
    'snow delivery in Qatar', 'HTC delivery in Qatar', 'hashesh delivery in Qatar',
    'coco delivery in Doha', 'weed delivery in Doha', 'vapes delivery in Doha',
    'snow delivery in Doha', 'HTC delivery in Doha', 'hashesh delivery in Doha',
    'coco delivery in UAE', 'weed delivery in UAE', 'vapes delivery in UAE',
    'snow delivery in UAE', 'coco delivery in Saudi Arabia',
    'weed delivery in Saudi Arabia', 'vapes delivery in Saudi Arabia',
    'coco delivery in Riyadh', 'weed delivery in Riyadh', 'vapes delivery in Riyadh',
    'coco delivery in Jeddah', 'weed delivery in Jeddah', 'vapes delivery in Jeddah',
    'coco delivery in Abu Dhabi', 'weed delivery in Abu Dhabi',
    'vapes delivery in Abu Dhabi', 'coco delivery in Sharjah',
    'weed delivery in Sharjah', 'vapes delivery in Sharjah',
    'coco delivery in Ajman', 'weed delivery in Ajman', 'vapes delivery in Ajman',
    'buy coco in Dubai', 'buy weed in Dubai', 'buy vapes in Dubai',
    'buy snow in Dubai', 'buy HTC in Dubai', 'buy hashesh in Dubai',
    'buy coco in Qatar', 'buy weed in Qatar', 'buy vapes in Qatar',
    'buy snow in Qatar', 'buy HTC in Qatar', 'buy hashesh in Qatar',
    'buy coco in Doha', 'buy weed in Doha', 'buy vapes in Doha',
    'buy snow in Doha', 'buy HTC in Doha', 'buy hashesh in Doha',
    'buy coco in UAE', 'buy weed in UAE', 'buy vapes in UAE',
    'buy snow in UAE', 'buy coco in Saudi Arabia', 'buy weed in Saudi Arabia',
    'buy vapes in Saudi Arabia', 'buy snow in Saudi Arabia',
    'buy coco in Riyadh', 'buy weed in Riyadh', 'buy vapes in Riyadh',
    'buy coco in Jeddah', 'buy weed in Jeddah', 'buy vapes in Jeddah',
    'buy coco in Abu Dhabi', 'buy weed in Abu Dhabi', 'buy vapes in Abu Dhabi',
    'buy coco in Sharjah', 'buy weed in Sharjah', 'buy vapes in Sharjah',
    'buy coco in Ajman', 'buy weed in Ajman', 'buy vapes in Ajman',
    'get coco in Dubai', 'get weed in Dubai', 'get vapes in Dubai',
    'get snow in Dubai', 'get coco in Qatar', 'get weed in Qatar',
    'get vapes in Qatar', 'get snow in Qatar', 'get coco in Doha',
    'get weed in Doha', 'get vapes in Doha', 'get snow in Doha',
    'get coco in UAE', 'get weed in UAE', 'get vapes in UAE',
    'get coco in Saudi Arabia', 'get weed in Saudi Arabia',
    'get vapes in Saudi Arabia', 'get coco in Riyadh',
    'get weed in Riyadh', 'get vapes in Riyadh', 'get coco in Jeddah',
    'get weed in Jeddah', 'get vapes in Jeddah', 'get coco in Abu Dhabi',
    'get weed in Abu Dhabi', 'get vapes in Abu Dhabi',
    'how to order coco in Dubai', 'how to order weed in Dubai',
    'how to order vapes in Dubai', 'how to order snow in Dubai',
    'how to order HTC in Dubai', 'how to order hashesh in Dubai',
    'how to order coco in Qatar', 'how to order weed in Qatar',
    'how to order vapes in Qatar', 'how to order snow in Qatar',
    'how to order coco in Doha', 'how to order weed in Doha',
    'how to order vapes in Doha', 'how to order snow in Doha',
    'how to order coco in UAE', 'how to order weed in UAE',
    'how to order vapes in UAE', 'how to order snow in UAE',
    'how to order coco in Saudi Arabia', 'how to order weed in Saudi Arabia',
    'how to order coco in Riyadh', 'how to order weed in Riyadh',
    'how to order coco in Jeddah', 'how to order weed in Jeddah',
    'how to order coco in Abu Dhabi', 'how to order weed in Abu Dhabi',
    'is there coco in Dubai', 'is there weed in Dubai', 'is there vapes in Dubai',
    'is there coco in Qatar', 'is there weed in Qatar', 'is there vapes in Qatar',
    'is there coco in Doha', 'is there weed in Doha', 'is there vapes in Doha',
    'is there coco in UAE', 'is there weed in UAE', 'is there vapes in UAE',
    'is there coco in Saudi Arabia', 'is there weed in Saudi Arabia',
    'is there coco in Riyadh', 'is there weed in Riyadh',
    'is there coco in Jeddah', 'is there weed in Jeddah',
    'is there coco in Abu Dhabi', 'is there weed in Abu Dhabi',
    'can you get coco in Dubai', 'can you get weed in Dubai',
    'can you get vapes in Dubai', 'can you get snow in Dubai',
    'can you get HTC in Dubai', 'can you get hashesh in Dubai',
    'can you get coco in Qatar', 'can you get weed in Qatar',
    'can you get vapes in Qatar', 'can you get snow in Qatar',
    'can you get HTC in Qatar', 'can you get hashesh in Qatar',
    'can you get coco in Doha', 'can you get weed in Doha',
    'can you get vapes in Doha', 'can you get snow in Doha',
    'can you get HTC in Doha', 'can you get hashesh in Doha',
    'can you get coco in UAE', 'can you get weed in UAE',
    'can you get vapes in UAE', 'can you get snow in UAE',
    'can you get coco in Saudi Arabia', 'can you get weed in Saudi Arabia',
    'can you get coco in Riyadh', 'can you get weed in Riyadh',
    'can you get coco in Jeddah', 'can you get weed in Jeddah',
    'can you get coco in Abu Dhabi', 'can you get weed in Abu Dhabi',
    'can you get coco in Sharjah', 'can you get weed in Sharjah',
    'coco near me Dubai', 'weed near me Dubai', 'vapes near me Dubai',
    'coco near me Qatar', 'weed near me Qatar', 'vapes near me Qatar',
    'coco near me Doha', 'weed near me Doha', 'vapes near me Doha',
    'coco near me UAE', 'weed near me UAE', 'vapes near me UAE',
    'coco near me Saudi Arabia', 'weed near me Saudi Arabia',
    'coco near me Riyadh', 'weed near me Riyadh', 'vapes near me Riyadh',
    'coco near me Jeddah', 'weed near me Jeddah', 'vapes near me Jeddah',
    'coco near me Abu Dhabi', 'weed near me Abu Dhabi',
    'buy coco online Dubai', 'buy weed online Dubai', 'buy vapes online Dubai',
    'buy coco online Qatar', 'buy weed online Qatar', 'buy vapes online Qatar',
    'buy coco online Doha', 'buy weed online Doha', 'buy vapes online Doha',
    'buy coco online UAE', 'buy weed online UAE', 'buy vapes online UAE',
    'buy coco online Saudi Arabia', 'buy weed online Saudi Arabia',
    'buy coco online Riyadh', 'buy weed online Riyadh',
    'buy coco online Jeddah', 'buy weed online Jeddah',
    'hash in Dubai', 'hash in Qatar', 'hash in Doha', 'hash in UAE',
    'hash in Saudi Arabia', 'hash in Riyadh', 'hash in Jeddah',
    'hashish in Dubai', 'hashish in Qatar', 'hashish in Doha',
    'Larycai pills in Dubai', 'Larycai pills in Qatar', 'Larycai pills in Doha',
    'HTC pills in Dubai', 'HTC pills in Qatar', 'HTC pills in Doha',
    'ice in Dubai', 'ice in Qatar', 'ice in Doha', 'ice in UAE',
    'LSD in Dubai', 'LSD in Qatar', 'LSD in Doha', 'LSD in UAE',
    'CBD oil in Dubai', 'CBD oil in Qatar', 'CBD oil in Doha',
    'THC vapes in Dubai', 'THC vapes in Qatar', 'THC vapes in Doha',
    'DXBCocoPlug Dubai', 'DXBCocoPlug Qatar', 'DXBCocoPlug Doha',
    'abu bilal Dubai', 'abu bilal Qatar', 'abu bilal Doha',
    'abubilal weed Dubai', 'abubilal weed Qatar', 'abubilal weed Doha',
    'Gulf weed plug', 'Gulf coco plug', 'Gulf vape plug',
    'discreet coco delivery Dubai', 'discreet weed delivery Dubai',
    'discreet coco delivery Qatar', 'discreet weed delivery Qatar',
    'discreet coco delivery Doha', 'discreet weed delivery Doha',
    'same day coco delivery Dubai', 'same day weed delivery Dubai',
    'same day vape delivery Dubai', 'same day snow delivery Dubai',
    'same day coco delivery Qatar', 'same day weed delivery Qatar',
    '24/7 coco delivery Dubai', '24/7 weed delivery Dubai',
    '24/7 vape delivery Dubai', '24/7 coco delivery Qatar',
    '24/7 weed delivery Qatar', '24/7 coco delivery Doha',
    'weed shop Dubai', 'weed shop Qatar', 'weed shop Doha',
    'weed shop UAE', 'weed shop Saudi', 'weed shop Riyadh',
    'coco shop Dubai', 'coco shop Qatar', 'coco shop Doha',
    'cannabis store Dubai', 'cannabis store Qatar', 'cannabis store Doha',
    'best weed in Dubai', 'best weed in Qatar', 'best weed in Doha',
    'best weed in UAE', 'best weed in Saudi', 'best weed in Riyadh',
    'best coco in Dubai', 'best coco in Qatar', 'best coco in Doha',
    'best vapes in Dubai', 'best vapes in Qatar', 'best vapes in Doha',
    'weed for sale in Dubai', 'weed for sale in Qatar', 'weed for sale in Doha',
    'weed for sale in UAE', 'weed for sale in Saudi Arabia',
    'weed for sale in Riyadh', 'weed for sale in Jeddah',
    'coco for sale in Dubai', 'coco for sale in Qatar', 'coco for sale in Doha',
    'vapes for sale in Dubai', 'vapes for sale in Qatar', 'vapes for sale in Doha',
    'marijuana Dubai', 'marijuana Qatar', 'marijuana Doha',
    'marijuana UAE', 'marijuana Saudi', 'marijuana Riyadh',
    'smoke delivery Dubai', 'smoke delivery Qatar', 'smoke delivery Doha',
    'coco delivery Dubai Marina', 'weed delivery Dubai Marina',
    'vapes delivery Dubai Marina', 'coco delivery Palm Jumeirah',
    'weed delivery Palm Jumeirah', 'vapes delivery Palm Jumeirah',
    'coco delivery JLT', 'weed delivery JLT', 'vapes delivery JLT',
    'coco delivery Al Barsha', 'weed delivery Al Barsha',
    'vapes delivery Al Barsha', 'coco delivery JVC', 'weed delivery JVC',
    'vapes delivery JVC', 'coco delivery Business Bay',
    'weed delivery Business Bay', 'coco delivery Downtown Dubai',
    'weed delivery Downtown Dubai', 'coco delivery Deira', 'weed delivery Deira',
    'coco delivery Bur Dubai', 'weed delivery Bur Dubai',
    'coco delivery Jumeirah', 'weed delivery Jumeirah',
    'coco delivery Lusail', 'weed delivery Lusail', 'vapes delivery Lusail',
    'coco delivery Al Wakrah', 'weed delivery Al Wakrah',
    'coco delivery Al Khor', 'weed delivery Al Khor',
    'coco delivery The Pearl', 'weed delivery The Pearl',
    'how to find weed plug in Dubai', 'how to find coco plug in Dubai',
    'how to find weed plug in Qatar', 'how to find coco plug in Qatar',
    'how to find weed plug in Doha', 'how to find coco plug in Doha',
    'weed dealer Dubai', 'weed dealer Qatar', 'weed dealer Doha',
    'weed dealer UAE', 'weed dealer Saudi', 'weed dealer Riyadh',
    'coco dealer Dubai', 'coco dealer Qatar', 'coco dealer Doha',
    'trusted plug Dubai', 'trusted plug Qatar', 'trusted plug Doha',
    'trusted plug UAE', 'trusted plug Saudi', 'trusted plug Riyadh',
    'reliable weed delivery Dubai', 'reliable weed delivery Qatar',
    'reliable weed delivery Doha', 'reliable coco delivery Dubai',
    'reliable coco delivery Qatar', 'reliable coco delivery Doha',
    'safe weed delivery Dubai', 'safe weed delivery Qatar',
    'safe weed delivery Doha', 'safe coco delivery Dubai',
    'safe coco delivery Qatar', 'safe coco delivery Doha',
    'express weed delivery Dubai', 'express weed delivery Qatar',
    'express coco delivery Dubai', 'express coco delivery Qatar',
    'night delivery weed Dubai', 'night delivery coco Dubai',
    'late night weed delivery Dubai', 'late night coco delivery Dubai',
    'Al Ain weed', 'Al Ain coco', 'Al Ain vapes', 'Al Ain snow',
    'Fujairah weed', 'Fujairah coco', 'Fujairah vapes', 'Fujairah snow',
    'RAK weed', 'RAK coco', 'RAK vapes', 'RAK snow',
    'Ras Al Khaimah weed', 'Ras Al Khaimah coco', 'Ras Al Khaimah vapes',
    'Umm Al Quwain weed', 'Umm Al Quwain coco', 'Umm Al Quwain vapes',
    'Makkah weed', 'Makkah coco', 'Medina weed', 'Medina coco',
    'Taif weed', 'Taif coco', 'Abha weed', 'Abha coco',
    'Jubail weed', 'Jubail coco', 'Yanbu weed', 'Yanbu coco',
    'where to get coco in Dubai', 'where to get weed in Dubai',
    'where to get vapes in Dubai', 'where to get coco in Qatar',
    'where to get weed in Qatar', 'where to get vapes in Qatar',
    'where to get coco in Doha', 'where to get weed in Doha',
    'where to get vapes in Doha', 'where to get coco in UAE',
    'where to get weed in UAE', 'where to get vapes in UAE',
    'where to get coco in Saudi Arabia', 'where to get weed in Saudi Arabia',
    'where to get coco in Riyadh', 'where to get weed in Riyadh',
    'where to get coco in Jeddah', 'where to get weed in Jeddah',
    'where to get coco in Abu Dhabi', 'where to get weed in Abu Dhabi',
    'where to get coco in Sharjah', 'where to get weed in Sharjah',
  ],
};

export default function PopularSearchTags() {
  const [expanded, setExpanded] = useState(false);

  const allTags = Object.values(seoTags).flat();
  const visibleTags = expanded ? allTags : allTags.slice(0, 80);

  return (
    <section className="bg-white py-14 border-t border-gray-100">
      <div className="max-w-7xl mx-auto px-6">
        <div className="mb-6">
          <h3 className="text-lg font-bold text-[#0a1f12] mb-1">Popular Search Tags</h3>
          <p className="text-sm text-gray-500">Find exactly what you&apos;re looking for across Qatar, Dubai, UAE &amp; Saudi Arabia. Click any tag to discover our products.</p>
        </div>

        {Object.entries(seoTags).map(([category, tags]) => (
          <div key={category} className="mb-5">
            <h4 className="text-xs font-bold uppercase tracking-wider text-[#1a472a] mb-2">{category}</h4>
            <div className="flex flex-wrap gap-1.5">
              {tags.map((tag, i) => (
                <span
                  key={i}
                  className="inline-block bg-[#f0f7f1] text-[#1a472a] text-xs px-2.5 py-1 rounded-full border border-[#1a472a]/10 hover:bg-[#1a472a] hover:text-white transition-colors cursor-pointer whitespace-nowrap"
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}